Repository Evarisk/gmao, pull requests merged in 2024-07, with the labels that each got.

#38 #25 [Ticket] add: qr code generation button for ticket without qr code
  class/actions_gmao.class.php
  class/gmaodocuments/gmaoticketdocument.class.php
  core/modules/modGMAO.class.php
Labels: 2, Enhancement

#19 #18 [add] ad odt document for vertical label
  documents/doctemplates/gmaoticketdocument/template_gmaoticketdocument-99012-89mm-36mm.odt
Labels: 1, Enhancement, ODT

#34 #20 [ODT] add: email in public url
  class/actions_gmao.class.php
  core/triggers/interface_99_modGmao_GmaoTriggers.class.php
  langs/fr_FR/gmao.lang
Labels: 1

#36 #35 [Hook] add: mass import serial number on inventory
  class/actions_gmao.class.php
  core/modules/modGMAO.class.php
  langs/fr_FR/gmao.lang
Labels: 5, Enhancement

#40 #27 [Mod] add: GMAO categories
  core/modules/modGMAO.class.php
  img/pictos_ticket/pictogram_Curative_64px.png
  img/pictos_ticket/pictogram_GMAO_64px.png
  img/pictos_ticket/pictogram_Improvement_64px.png
  img/pictos_ticket/pictogram_Preventive_64px.png
  langs/fr_FR/gmao.lang
Labels: 2, Enhancement

#42 #41 [Mod] add: new version number 1.1.0
  README.md
  core/modules/modGMAO.class.php
  core/triggers/interface_99_modGmao_GmaoTriggers.class.php
Labels: 0, Enhancement
